[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "samuel"
version = "0.1.0"
description = "Systems Accounting Manager (SAM) System - ORM and Webapp"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "NCAR/CISL internal use" }
authors = [
  { name = "NCAR/CISL", email = "csg@ucar.edu" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Framework :: Flask",
    "Private :: Do Not Upload"
]

dependencies = [
    "cryptography",
    "flask",
    "flask-admin",
    "flask-login",
    "flask-sqlalchemy",
    "gunicorn",
    "marshmallow-sqlalchemy",
    "matplotlib",
    "pymysql",
    "python-dotenv",
    "pyyaml",
    "requests",
    "rich",
    "sqlalchemy",
    "tqdm",
    "click",
]

[project.scripts]
sam-search = "sam_search_cli:cli"
sam-status = "system_status:main"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-timeout",
]
dev = ["samuel[test]", "jupyterlab", "pandas"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]